package com.example.healthmap.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val md_theme_light_primary = Color(0xFF006874)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF97F0FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F23)
val md_theme_light_secondary = Color(0xFF4A6267)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCE8ED)
val md_theme_light_onSecondaryContainer = Color(0xFF051F23)
val md_theme_light_tertiary = Color(0xFF525E7D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDAE2FF)
val md_theme_light_onTertiaryContainer = Color(0xFF0E1B37)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFCFE)
val md_theme_light_onBackground = Color(0xFF191C1D)
val md_theme_light_surface = Color(0xFFFBFCFE)
val md_theme_light_onSurface = Color(0xFF191C1D)
val md_theme_light_surfaceVariant = Color(0xFFDBE4E6)
val md_theme_light_onSurfaceVariant = Color(0xFF3F484A)
val md_theme_light_outline = Color(0xFF6F797A)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F2)
val md_theme_light_inverseSurface = Color(0xFF2D3132)
val md_theme_light_inversePrimary = Color(0xFF4DD0E1)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFF4DD0E1)
val md_theme_dark_onPrimary = Color(0xFF00363A)
val md_theme_dark_primaryContainer = Color(0xFF004F58)
val md_theme_dark_onPrimaryContainer = Color(0xFF97F0FF)
val md_theme_dark_secondary = Color(0xFFB0CCD1)
val md_theme_dark_onSecondary = Color(0xFF1B3438)
val md_theme_dark_secondaryContainer = Color(0xFF324B4F)
val md_theme_dark_onSecondaryContainer = Color(0xFFCCE8ED)
val md_theme_dark_tertiary = Color(0xFFBCC6EA)
val md_theme_dark_onTertiary = Color(0xFF26304D)
val md_theme_dark_tertiaryContainer = Color(0xFF3C4664)
val md_theme_dark_onTertiaryContainer = Color(0xFFDAE2FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0F1415)
val md_theme_dark_onBackground = Color(0xFFDFE3E4)
val md_theme_dark_surface = Color(0xFF0F1415)
val md_theme_dark_onSurface = Color(0xFFDFE3E4)
val md_theme_dark_surfaceVariant = Color(0xFF3F484A)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CA)
val md_theme_dark_outline = Color(0xFF899294)
val md_theme_dark_inverseOnSurface = Color(0xFF0F1415)
val md_theme_dark_inverseSurface = Color(0xFFDFE3E4)
val md_theme_dark_inversePrimary = Color(0xFF006874)

// Custom App Colors
val AppBlue = Color(0xFF2196F3)
val AppGreen = Color(0xFF4CAF50)
val AppOrange = Color(0xFFFF9800)
val AppRed = Color(0xFFF44336)
val AppPurple = Color(0xFF9C27B0)

// Neutral Colors
val Neutral10 = Color(0xFF191C1D)
val Neutral20 = Color(0xFF2D3132)
val Neutral30 = Color(0xFF434748)
val Neutral40 = Color(0xFF5B5E5F)
val Neutral50 = Color(0xFF747878)
val Neutral60 = Color(0xFF8E9192)
val Neutral70 = Color(0xFFA9ACAD)
val Neutral80 = Color(0xFFC4C7C8)
val Neutral90 = Color(0xFFE0E3E4)
val Neutral95 = Color(0xFFEFF1F2)
val Neutral99 = Color(0xFFFBFCFE)

// Common UI Colors
val CardBackground = Color(0xFFF8F9FA)
val DividerColor = Color(0xFFE0E0E0)
val SuccessColor = Color(0xFF4CAF50)
val WarningColor = Color(0xFFFF9800)
val InfoColor = Color(0xFF2196F3)